//
//  File.swift
//  
//
//  Created by YuAo on 2020/3/16.
//

import Foundation
import ArgumentParser
import URLExpressibleByArgument
import RasterSourceLocator

public struct UmbrellaHeaderGenerator: ParsableCommand {
    
    @Argument(help: "The root directory of the Raster repo.")
    var projectRoot: URL
    
    enum CodingKeys: CodingKey {
        case projectRoot
    }
    
    private let fileManager = FileManager()
    
    public init() { }
    
    public func run() throws {
        let directoryURL = RasterSourcesRootURL(in: projectRoot)
        let privateHeaderFiles = self.excludedHeaderFileNames
        let headerFileNames = self.headerFileNames(in: directoryURL).filter({ !privateHeaderFiles.contains($0) })
        let content = """
        // Raster Umbrella Header
        // Auto Generated by `swift run main boilerplate-generator`
        
        \(headerFileNames.reduce("", { result, value in return result + "#import \"\(value)\"\n"}))
        FOUNDATION_EXPORT double RasterVersionNumber;
        FOUNDATION_EXPORT const unsigned char RasterVersionString[];
        
        """
        try! content.write(to: directoryURL.appendingPathComponent("Raster.h"), atomically: true, encoding: .utf8)
    }
    
    private let excludedHeaderFileNames: Set<String> = [
        "MTIPrint.h",
        "MTIDefer.h",
        "MTIHasher.h",
        "MTIImageRenderingContext+Internal.h",
        "MTIBlendFormulaSupport.h",
        "MTIContext+Internal.h",
        "MTIImage+Promise.h",
        "Raster.h"
    ]
    
    private func headerFileNames(in directory: URL) -> [String] {
        var fileNames: [String] = []
        if let contents = try? FileManager.default.contentsOfDirectory(at: directory, includingPropertiesForKeys: nil, options: []) {
            for url in contents.sorted(by: { $0.path < $1.path }) {
                if url.pathExtension == "h" {
                    fileNames.append(url.lastPathComponent)
                } else {
                    let isDirectory = try? url.resourceValues(forKeys: Set([URLResourceKey.isDirectoryKey])).isDirectory
                    if isDirectory ?? false {
                        fileNames.append(contentsOf: headerFileNames(in: url))
                    }
                }
            }
        }
        return fileNames
    }
}
